application:
  version: 1.0.0
server:
  port: 8080
logging:
  level:
    # root: info [[ default logging level ]]
    com.quathar.codebay: debug
spring:
  application:
    name: Codebay
  datasource:
    url: jdbc:h2:mem:codebay
    username: Q
    # password: Q
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
